on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.23.4"

      - name: Setup GO environment
        run: |
          go mod download
          go get -t .

      - name: Vet
        run: |
          go vet ./...

      - name: Unit tests
        run: |
          sudo go test ./... -coverprofile coverage.out -covermode count
          sudo go tool cover -func coverage.out

      - name: Build
        run: |
          go build -o wireframe
